name: Deploy to Heroku

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh
          
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
        run: |
          git remote remove heroku || true
          heroku buildpacks:clear --app $HEROKU_APP_NAME
          heroku buildpacks:set heroku/python --app $HEROKU_APP_NAME
          heroku buildpacks:add --index 1 https://github.com/heroku/heroku-buildpack-google-chrome --app $HEROKU_APP_NAME
          heroku config:set DISABLE_COLLECTSTATIC=1 --app $HEROKU_APP_NAME
          heroku config:set CHROME_BINARY_PATH=/app/.apt/usr/bin/google-chrome --app $HEROKU_APP_NAME
          heroku git:remote --app $HEROKU_APP_NAME
          git push heroku main:main --force
